version: "2"

services:
  main:
    build: .

  #  external_links:
    links:
      - "postgres:postgres"
      - "redis:redis"

    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://root:root@postgres/hello_heroku_development?pool=2
      REDIS_URL: redis://redis
      PORT: 5000

    ports:
      - "5000:5000"

    volumes:
      - ".:/products"

    command: "/products/run.sh"

  postgres:
    image: postgres

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  redis:
    image: redis

    ports:
      - "6379:6379"
